version: '3.8'
services:

  dapp:
    depends_on:
      - deploy
    build:
      context: ./dapp
      dockerfile: Dockerfile
    ports:
      - 3001:3001
      - 3002:3002

  


  anvil:
    build:
      context: ./smartcontracts
      dockerfile: Dockerfile.anvil
    ports:
      - 8545:8545

  deploy:
    depends_on:
      - anvil
    build:
      context: ./smartcontracts
      dockerfile: Dockerfile.deploy