version: '3.8'
services:


  curso:
    build:
      context: ./dapp/curso
      dockerfile: Dockerfile
   
  servidor:
    build:
      context: ./dapp/servidor
      dockerfile: Dockerfile


  dapp:
    depends_on:
      - curso
      - servidor
      - deploy
    build:
      context: ./dapp
      dockerfile: Dockerfile
    ports:
      - 3001:3001
      - 3002:3002

  


  anvil:
    build:
      context: ./smartcontracts
      dockerfile: Dockerfile.anvil
    ports:
      - 8545:8545

  deploy:
    depends_on:
      - anvil
    build:
      context: ./smartcontracts
      dockerfile: Dockerfile.deploy